name: Client
   
on:
  push:
    branches: 
      - main
   
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@main
        with:
          ref: main
      - name: .env setting
        run: |
          echo "REACT_APP_BASE_URL=$REACT_APP_BASE_URL" > .env
      - name: git clone
        uses: actions/checkout@v2
   
      - name: npm install
        run: npm install
   
      - name: npm build
        run: npm run build
        env:
          CI: false
   
      - uses: awact/s3-sync-action@v1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: './build'
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}